# Generated by Django 5.2.15 on 2026-06-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan sana')),
            ],
            options={
                'verbose_name': 'Aloqa xabari',
                'verbose_name_plural': 'Aloqa xabarlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('book', 'Kitob'), ('people', 'Odamlar'), ('medal', 'Medal'), ('monitor', 'Monitor / onlayn'), ('globe', 'Globus')], default='book', help_text='Statistika kartochkasidagi ikonka', max_length=50, verbose_name='Ikonka')),
                ('value', models.CharField(help_text='Masalan: 2000+, 10+, Bepul', max_length=100, verbose_name='Qiymat')),
                ('label', models.CharField(help_text='Masalan: Nashr etilgan kitoblar', max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(help_text='Kartochka ostidagi qisqa izoh', verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, help_text="Kichik raqam chapdan boshlab ko'rinadi", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, help_text="O'chirilsa bosh sahifada ko'rinmaydi", verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Bosh sahifa statistikasi',
                'verbose_name_plural': 'Bosh sahifa statistikasi',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Obuna sanasi')),
            ],
            options={
                'verbose_name': 'Obunachi',
                'verbose_name_plural': 'Obunachilar',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Masalan: Sifatli nashrlar', max_length=200, verbose_name='Xizmat nomi')),
                ('slug', models.SlugField(help_text='Lotin harflarda. Masalan: sifatli-nashrlar', unique=True, verbose_name='Slug (URL)')),
                ('short_description', models.CharField(help_text="Bosh sahifa kartochkasida ko'rinadigan qisqa matn", max_length=300, verbose_name='Qisqa tavsif')),
                ('description', models.TextField(help_text='Xizmatlar sahifasidagi batafsil matn', verbose_name="To'liq tavsif")),
                ('icon', models.CharField(choices=[('book', 'Kitob'), ('badge', 'Medal / sifat'), ('people', 'Odamlar'), ('truck', 'Yetkazib berish'), ('support', "Qo'llab-quvvatlash"), ('lock', 'Xavfsizlik'), ('print', 'Bosma')], default='book', help_text="Bosh sahifada ko'rinadigan ikonka turi", max_length=50, verbose_name='Ikonka')),
                ('order', models.PositiveIntegerField(default=0, help_text="Kichik raqam yuqorida ko'rinadi", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, help_text="O'chirilsa bosh sahifada ko'rinmaydi", verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar (bosh sahifa)',
                'ordering': ['order'],
            },
        ),
    ]
