# Generated by Django 5.2.15 on 2026-06-19 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: Din, Ilm-fan, Tarbiya', max_length=100, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(help_text='Lotin harflarda. Masalan: din', unique=True, verbose_name='Slug (URL)')),
                ('description', models.TextField(blank=True, help_text='Kategoriya haqida qisqa izoh (ixtiyoriy)', verbose_name='Tavsif')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text="Kichik raqam yuqorida ko'rinadi", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, help_text="O'chirilsa filtr va ro'yxatda ko'rinmaydi", verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Maqola kategoriyasi',
                'verbose_name_plural': 'Maqola kategoriyalari',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Masalan: Yangi nashrlar, Tadbirlar, E'lonlar", max_length=100, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(help_text='Lotin harflarda. Masalan: yangi-nashrlar', unique=True, verbose_name='Slug (URL)')),
                ('description', models.TextField(blank=True, help_text='Kategoriya haqida qisqa izoh (ixtiyoriy)', verbose_name='Tavsif')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text="Kichik raqam yuqorida ko'rinadi", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, help_text="O'chirilsa filtr va ro'yxatda ko'rinmaydi", verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Yangilik kategoriyasi',
                'verbose_name_plural': 'Yangilik kategoriyalari',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Maqola sarlavhasi', max_length=300, verbose_name='Sarlavha')),
                ('slug', models.SlugField(help_text="Lotin harflarda, noyob bo'lishi kerak", unique=True, verbose_name='Slug (URL)')),
                ('excerpt', models.TextField(help_text="Ro'yxat sahifasida ko'rinadigan qisqa xulosa", verbose_name='Qisqa matn')),
                ('content', models.TextField(help_text="Maqolaning to'liq matni", verbose_name="To'liq matn")),
                ('image_url', models.URLField(help_text='Maqola asosiy rasmi URL manzili', verbose_name='Rasm havolasi')),
                ('pdf_url', models.URLField(blank=True, help_text="To'liq o'qish uchun PDF havolasi (ixtiyoriy)", verbose_name='PDF havola')),
                ('author_name', models.CharField(default='BUKHARA HAMD PRINT', help_text='Maqola muallifi yoki manba', max_length=200, verbose_name='Muallif')),
                ('published_at', models.DateField(help_text="Maqola e'lon qilingan sana", verbose_name='Nashr sanasi')),
                ('views', models.PositiveIntegerField(default=0, help_text='Sahifa ochilishlari soni', verbose_name="Ko'rishlar")),
                ('reading_time', models.PositiveIntegerField(default=8, help_text="Taxminiy o'qish vaqti daqiqalarda", verbose_name="O'qish vaqti (daqiqa)")),
                ('is_published', models.BooleanField(default=True, help_text="O'chirilsa saytda ko'rinmaydi", verbose_name='Nashr etilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('category', models.ForeignKey(help_text='Avval maqola kategoriyasini tanlang yoki yarating', on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='blog.articlecategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Yangilik sarlavhasi', max_length=300, verbose_name='Sarlavha')),
                ('slug', models.SlugField(help_text="Lotin harflarda, noyob bo'lishi kerak", unique=True, verbose_name='Slug (URL)')),
                ('excerpt', models.TextField(help_text="Ro'yxat sahifasida ko'rinadigan qisqa xulosa", verbose_name='Qisqa matn')),
                ('content', models.TextField(help_text="Yangilikning to'liq matni (HTML yoki oddiy matn)", verbose_name="To'liq matn")),
                ('image_url', models.URLField(help_text='Yangilik asosiy rasmi URL manzili', verbose_name='Rasm havolasi')),
                ('published_at', models.DateField(help_text="Yangilik e'lon qilingan sana", verbose_name='Nashr sanasi')),
                ('views', models.PositiveIntegerField(default=0, help_text='Sahifa ochilishlari soni', verbose_name="Ko'rishlar")),
                ('reading_time', models.PositiveIntegerField(default=5, help_text="Taxminiy o'qish vaqti daqiqalarda", verbose_name="O'qish vaqti (daqiqa)")),
                ('is_published', models.BooleanField(default=True, help_text="O'chirilsa saytda ko'rinmaydi", verbose_name='Nashr etilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('category', models.ForeignKey(help_text='Avval yangilik kategoriyasini tanlang yoki yarating', on_delete=django.db.models.deletion.PROTECT, related_name='news_posts', to='blog.newscategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_at'],
            },
        ),
    ]
