# Generated by Django 5.2.15 on 2026-06-19 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Kitob muallifining to'liq ismi", max_length=200, verbose_name='Muallif ismi')),
                ('slug', models.SlugField(help_text='Lotin harflarda. Masalan: abdulloh-qodiriy', unique=True, verbose_name='Slug (URL)')),
                ('bio', models.TextField(blank=True, help_text="Muallif haqida qisqa ma'lumot (ixtiyoriy)", verbose_name='Biografiya')),
                ('photo_url', models.URLField(blank=True, help_text='Muallif rasmi URL manzili (ixtiyoriy)', verbose_name='Rasm havolasi')),
            ],
            options={
                'verbose_name': 'Muallif',
                'verbose_name_plural': 'Mualliflar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: Monografiyalar, Darsliklar', max_length=100, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(help_text="Lotin harflarda, bo'sh joysiz. Masalan: monografiyalar", unique=True, verbose_name='Slug (URL)')),
                ('description', models.TextField(blank=True, help_text="Bosh sahifa va kategoriya kartochkasida ko'rinadigan qisqa matn", verbose_name='Tavsif')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text="Kichik raqam yuqorida ko'rinadi (0, 1, 2...)", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, help_text="O'chirilsa saytda ko'rinmaydi", verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Kitob kategoriyasi',
                'verbose_name_plural': 'Kitob kategoriyalari',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Kitobning to'liq sarlavhasi", max_length=300, verbose_name='Kitob nomi')),
                ('slug', models.SlugField(help_text="Lotin harflarda, noyob bo'lishi kerak", unique=True, verbose_name='Slug (URL)')),
                ('cover_url', models.URLField(help_text='Kitob muqovasi rasm URL manzili', verbose_name='Muqova rasmi')),
                ('description', models.TextField(blank=True, help_text="Kitob haqida to'liq matn", verbose_name='Tavsif')),
                ('publisher', models.CharField(default='BUKHARA HAMD PRINT', help_text='Nashriyot nomi', max_length=200, verbose_name='Nashriyot')),
                ('year', models.PositiveIntegerField(default=2024, help_text='Masalan: 2024', verbose_name='Nashr yili')),
                ('pages', models.PositiveIntegerField(default=0, help_text='Kitob sahifalari soni', verbose_name='Sahifalar soni')),
                ('file_format', models.CharField(default='PDF', help_text='Masalan: PDF, EPUB', max_length=20, verbose_name='Fayl formati')),
                ('file_size', models.CharField(blank=True, help_text='Masalan: 4.2 MB', max_length=50, verbose_name='Fayl hajmi')),
                ('pdf_url', models.URLField(blank=True, help_text="PDF yuklab olish uchun to'g'ridan-to'g'ri havola", verbose_name='PDF havola')),
                ('read_online_url', models.URLField(blank=True, help_text="Brauzerda o'qish uchun havola (ixtiyoriy)", verbose_name="Onlayn o'qish havolasi")),
                ('table_of_contents', models.TextField(blank=True, help_text='Har bir bob yangi qatorda yoziladi', verbose_name='Mundarija')),
                ('language', models.CharField(default="O'zbekcha", help_text="Masalan: O'zbekcha, Ruscha", max_length=50, verbose_name='Til')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Statistika uchun (avtomatik oshirilishi mumkin)', verbose_name='Yuklab olishlar')),
                ('about_points', models.TextField(blank=True, help_text='Har bir punkt yangi qatorda', verbose_name='Kitob haqida punktlar')),
                ('views', models.PositiveIntegerField(default=0, help_text='Sahifa ochilishlari soni', verbose_name="Ko'rishlar")),
                ('is_featured', models.BooleanField(default=False, help_text="Bosh sahifada yoki maxsus ro'yxatda ko'rsatish uchun", verbose_name='Tanlangan kitob')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('author', models.ForeignKey(help_text="Avval admin paneldan muallif qo'shing", on_delete=django.db.models.deletion.CASCADE, related_name='books', to='catalog.author', verbose_name='Muallif')),
                ('category', models.ForeignKey(help_text='Kitob qaysi kategoriyaga tegishli', on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalog.bookcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
                'ordering': ['-created_at'],
            },
        ),
    ]
