# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='read_online_url',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_url',
            field=models.URLField(
                blank=True,
                help_text='Muqova rasmi uchun tashqi URL (ixtiyoriy)',
                verbose_name='Muqova havolasi',
            ),
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(
                blank=True,
                help_text='Kompyuterdan muqova rasmini yuklang (ixtiyoriy)',
                upload_to='books/covers/',
                verbose_name='Muqova fayli',
            ),
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(
                blank=True,
                help_text='Kompyuterdan PDF fayl yuklang (ixtiyoriy)',
                upload_to='books/pdf/',
                verbose_name='PDF fayl',
            ),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_url',
            field=models.URLField(
                blank=True,
                help_text='PDF uchun tashqi URL havola (ixtiyoriy)',
                verbose_name='PDF havola',
            ),
        ),
    ]
